# Generated by Django 6.0.2 on 2026-02-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kategori Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ünite Başlığı')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıralama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Soru Metni')),
                ('option_a', models.CharField(max_length=200, verbose_name='A Şıkkı')),
                ('option_b', models.CharField(max_length=200, verbose_name='B Şıkkı')),
                ('option_c', models.CharField(max_length=200, verbose_name='C Şıkkı')),
                ('option_d', models.CharField(max_length=200, verbose_name='D Şıkkı')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Doğru Şık')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.unit')),
            ],
        ),
    ]
