# Generated by Django 6.0.2 on 2026-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name="Hâkim'in Açıklaması"),
        ),
        migrations.AddField(
            model_name='question',
            name='options_json',
            field=models.TextField(default='[]', help_text='Örn: [{"id": "A", "text": "Su", "image": "url"}]', verbose_name='Şıklar (JSON)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Klasik Çoktan Seçmeli'), ('image_selection', 'Resim Seçmeli (Su Çeşitleri)')], default='multiple_choice', max_length=20, verbose_name='Soru Tipi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=10, verbose_name="Doğru Cevap ID'si (Örn: A)"),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Soru Metni'),
        ),
    ]
