# Generated by Django 5.1.5 on 2026-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_finalize_lesson_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='Cihaz Kimliği')),
                ('hearts', models.PositiveSmallIntegerField(default=3, verbose_name='Can')),
                ('hearts_max', models.PositiveSmallIntegerField(default=3, verbose_name='Azami Can')),
                ('last_heart_lost_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Can Kaybı')),
                ('gems', models.PositiveIntegerField(default=0, verbose_name='Elmas')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='XP')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Seri')),
                ('completed_lesson_ids', models.JSONField(default=list, verbose_name='Tamamlanan Dersler')),
            ],
            options={
                'verbose_name': 'Kullanıcı İlerlemesi',
                'verbose_name_plural': 'Kullanıcı İlerlemeleri',
            },
        ),
    ]
